# This file was generated by GoReleaser. DO NOT EDIT.
cask "groot" do
  zap trash: "~/.config/groot"
  caveats <<~EOS
    Sample configuration is not bundled with the Homebrew cask.
    Copy from the upstream repo or generate with
    `groot --print-sample-config > ~/.config/groot/groot.yml`.
  EOS

  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "94d3d6676ff7eed6c3b060ab87fd4b039d8ce2c4d4c31e71a32eac43a2587dd9"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
    on_arm do
      sha256 "882dcd2f726e7a09f321cea0afc86d0579276aa31ee97269647de8342ac98d81"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ef4fec77643ba8bec94bbc9470594d72e1cf446db5608c5157d18dd9cb6c51d"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
    on_arm do
      sha256 "d16eff804b8feee2108ae5396550a54128098f8d2886825d30805285107f4f6b"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
  end

  name "groot"
  desc "Read-only log and context collector for Kubernetes (also ships the kubectl-groot plugin)"
  homepage "https://github.com/hrodrig/groot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "groot"
  binary "kubectl-groot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/groot"]
    end
  end

  # No zap stanza required

end
