# This file was generated by GoReleaser. DO NOT EDIT.
cask "groot" do
  livecheck do
    url :stable
    strategy :github_latest_release
  end
  zap trash: "~/.config/groot"
  caveats <<~EOS
    Sample configuration is not bundled with the Homebrew cask.
    Copy from the upstream repo or generate with
    `groot --print-sample-config > ~/.config/groot/groot.yml`.
  EOS

  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "08c417dc72e67f38cf4e511d990883b92de5a2c7521a77f22e53202ae44586e1"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
    on_arm do
      sha256 "aa034c33dc572818150bb09b8d430e4e3e1dbeef42ff42394bc8e6c2cba4a380"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
  end

  on_linux do
    on_intel do
      sha256 "29153a3711d9c3f57eae2633a999b570e42b11b9c8fb1662163d3ffc86895346"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
    on_arm do
      sha256 "2b57a0a1cda1dd01f6ce703f2a54842b248da2b356fa010833735f6f51b158e6"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
  end

  name "groot"
  desc "Read-only log and context collector for Kubernetes"
  homepage "https://github.com/hrodrig/groot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "groot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/groot"]
    end
  end

  # No zap stanza required

end
