# This file was generated by GoReleaser. DO NOT EDIT.
cask "groot" do
  livecheck do
    url :stable
    strategy :github_latest_release
  end
  zap trash: "~/.config/groot"
  caveats <<~EOS
    Sample configuration is not bundled with the Homebrew cask.
    Copy from the upstream repo or generate with
    `groot --print-sample-config > ~/.config/groot/groot.yml`.
  EOS

  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "9726d113f90be63824fb9e379a1fc65c67c9c7df81fb34bd2d6981e5c2bdef9e"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
    on_arm do
      sha256 "6ffa219e33e805b8cca41186d42a5b4a165ba7bc0556d7afcd0171d2b73aab3b"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ac84b4566b6996433e4447a0c881133e8c2ce8f51825d7c9e512d41f2350a6e"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
    on_arm do
      sha256 "b4c3b36d9e1dd6b1a1e5955f2c340c9e8ae079af913dc2532a0ee1a9055e3abb"
      url "https://github.com/hrodrig/groot/releases/download/v#{version}/groot_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/groot/"
    end
  end

  name "groot"
  desc "Read-only log and context collector for Kubernetes"
  homepage "https://github.com/hrodrig/groot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "groot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/groot"]
    end
  end

  # No zap stanza required

end
